version: '3.7'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iliad
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony_app
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/iliad?serverVersion=13&charset=utf8
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - 4200:4200
    networks:
      - app-network
    volumes:
      - /app/node_modules
      - ./frontend:/app
    command: ng serve --host 0.0.0.0

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
