version: '3.7'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iliad
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony_app
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/iliad
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    command: >
      /bin/bash -c "php bin/console doctrine:migrations:migrate --no-interaction && php bin/console cache:clear && php bin/console doctrine:fixtures:load  --no-interaction && php -S 0.0.0.0:8000 -t public"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - 4200:4200
    networks:
      - app-network
    volumes:
      - /app/node_modules
      - ./frontend:/app
    command: >
        /bin/bash -c "npm install && ng serve --host 0.0.0.0 --poll=1000"
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
